name: otogapo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animated_text_kit: ^4.2.2
  authentication_repository:
    path: packages/authentication_repository
  auto_route: ^7.9.2
  bloc: ^8.1.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.0.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  extended_image: ^8.2.1
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_flavor: ^3.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  google_sign_in: ^5.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_serializable: ^6.8.0
  local_storage:
    path: packages/local_storage
  otogapo_core:
    path: packages/otogapo_core
  package_info_plus: ^8.0.0
  validators: ^3.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    # - assets/fonts/
