name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build_runner: ^2.4.9
  cloud_firestore: ^5.0.1
  dio: ^5.1.2
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  freezed: ^2.5.2
  fresh: ^0.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  fresh_dio: ^0.4.0
  local_storage:
    path: ../local_storage
  freezed_annotation: ^2.4.3

dev_dependencies:
  json_serializable: ^6.8.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  json_annotation: ^4.9.0
